/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.73.0
  Forc version: 0.49.2
  Fuel-Core version: 0.22.0
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Option, Enum, Vec } from "./common";

export enum ErrorInput { GenericError = 'GenericError', MaxOwnersReached = 'MaxOwnersReached', AlreadyOwner = 'AlreadyOwner', NotOwner = 'NotOwner', DuplicatedOwner = 'DuplicatedOwner', OwnersCannotBeEmpty = 'OwnersCannotBeEmpty', ThresholdCannotBeZero = 'ThresholdCannotBeZero', ThresholdCannotBeGreaterThanOwners = 'ThresholdCannotBeGreaterThanOwners', ThresholdNotReached = 'ThresholdNotReached', ThresholdStillReachable = 'ThresholdStillReachable', AlreadyVoted = 'AlreadyVoted', InvalidTxId = 'InvalidTxId', Unauthorized = 'Unauthorized', NotInitialized = 'NotInitialized', AlreadyInitialized = 'AlreadyInitialized' };
export enum ErrorOutput { GenericError = 'GenericError', MaxOwnersReached = 'MaxOwnersReached', AlreadyOwner = 'AlreadyOwner', NotOwner = 'NotOwner', DuplicatedOwner = 'DuplicatedOwner', OwnersCannotBeEmpty = 'OwnersCannotBeEmpty', ThresholdCannotBeZero = 'ThresholdCannotBeZero', ThresholdCannotBeGreaterThanOwners = 'ThresholdCannotBeGreaterThanOwners', ThresholdNotReached = 'ThresholdNotReached', ThresholdStillReachable = 'ThresholdStillReachable', AlreadyVoted = 'AlreadyVoted', InvalidTxId = 'InvalidTxId', Unauthorized = 'Unauthorized', NotInitialized = 'NotInitialized', AlreadyInitialized = 'AlreadyInitialized' };
export type IdentityInput = Enum<{ Address: AddressInput, ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput, ContractId: ContractIdOutput }>;

export type AddressInput = { value: string };
export type AddressOutput = AddressInput;
export type ContractIdInput = { value: string };
export type ContractIdOutput = ContractIdInput;
export type TransactionInput = { to: IdentityInput, data: BigNumberish };
export type TransactionOutput = { to: IdentityOutput, data: BN };

interface FuelMultisigAbiInterface extends Interface {
  functions: {
    add_owner: FunctionFragment;
    approve_tx: FunctionFragment;
    change_threshold: FunctionFragment;
    constructor: FunctionFragment;
    execute_tx: FunctionFragment;
    get_active_tx_ids: FunctionFragment;
    get_next_tx_id: FunctionFragment;
    get_owners: FunctionFragment;
    get_threshold: FunctionFragment;
    get_tx: FunctionFragment;
    get_tx_approval_by_owner: FunctionFragment;
    get_tx_approval_count: FunctionFragment;
    get_tx_rejection_count: FunctionFragment;
    is_owner: FunctionFragment;
    propose_tx: FunctionFragment;
    reject_tx: FunctionFragment;
    remove_owner: FunctionFragment;
    remove_tx: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'add_owner', values: [IdentityInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'approve_tx', values: [BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'change_threshold', values: [BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'constructor', values: [BigNumberish, Vec<IdentityInput>]): Uint8Array;
  encodeFunctionData(functionFragment: 'execute_tx', values: [BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_active_tx_ids', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'get_next_tx_id', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'get_owners', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'get_threshold', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'get_tx', values: [BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_tx_approval_by_owner', values: [BigNumberish, IdentityInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_tx_approval_count', values: [BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_tx_rejection_count', values: [BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'is_owner', values: [IdentityInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'propose_tx', values: [TransactionInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'reject_tx', values: [BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'remove_owner', values: [IdentityInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'remove_tx', values: [BigNumberish]): Uint8Array;

  decodeFunctionData(functionFragment: 'add_owner', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'approve_tx', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'change_threshold', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'constructor', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'execute_tx', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_active_tx_ids', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_next_tx_id', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_owners', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_threshold', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_tx', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_tx_approval_by_owner', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_tx_approval_count', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_tx_rejection_count', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'is_owner', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'propose_tx', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'reject_tx', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'remove_owner', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'remove_tx', data: BytesLike): DecodedValue;
}

export class FuelMultisigAbi extends Contract {
  interface: FuelMultisigAbiInterface;
  functions: {
    add_owner: InvokeFunction<[owner: IdentityInput], void>;
    approve_tx: InvokeFunction<[tx_id: BigNumberish], void>;
    change_threshold: InvokeFunction<[threshold: BigNumberish], void>;
    constructor: InvokeFunction<[threshold: BigNumberish, owners_list: Vec<IdentityInput>], void>;
    execute_tx: InvokeFunction<[tx_id: BigNumberish], void>;
    get_active_tx_ids: InvokeFunction<[], Vec<BN>>;
    get_next_tx_id: InvokeFunction<[], BN>;
    get_owners: InvokeFunction<[], Vec<IdentityOutput>>;
    get_threshold: InvokeFunction<[], number>;
    get_tx: InvokeFunction<[tx_id: BigNumberish], Option<TransactionOutput>>;
    get_tx_approval_by_owner: InvokeFunction<[tx_id: BigNumberish, owner: IdentityInput], Option<boolean>>;
    get_tx_approval_count: InvokeFunction<[tx_id: BigNumberish], Option<number>>;
    get_tx_rejection_count: InvokeFunction<[tx_id: BigNumberish], Option<number>>;
    is_owner: InvokeFunction<[owner: IdentityInput], boolean>;
    propose_tx: InvokeFunction<[tx: TransactionInput], void>;
    reject_tx: InvokeFunction<[tx_id: BigNumberish], void>;
    remove_owner: InvokeFunction<[owner: IdentityInput], void>;
    remove_tx: InvokeFunction<[tx_id: BigNumberish], void>;
  };
}
