/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.2
  Forc version: 0.60.0
  Fuel-Core version: 0.27.0
*/

export type { FuelMultisigAbi } from './FuelMultisigAbi';

export { FuelMultisigAbi__factory } from './factories/FuelMultisigAbi__factory';
