/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.81.0
  Forc version: 0.49.3
  Fuel-Core version: 0.22.1
*/

export type { FuelMultisigAbi } from './FuelMultisigAbi';

export { FuelMultisigAbi__factory } from './factories/FuelMultisigAbi__factory';
