/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.2
  Forc version: 0.60.0
  Fuel-Core version: 0.27.0
*/

import { Interface, Contract, ContractFactory } from "fuels";
import type { Provider, Account, AbstractAddress, BytesLike, DeployContractOptions, StorageSlot } from "fuels";
import type { FuelMultisigAbi, FuelMultisigAbiInterface } from "../FuelMultisigAbi";

const _abi = {
  "encoding": "1",
  "types": [
    {
      "typeId": 0,
      "type": "()",
      "components": [],
      "typeParameters": null
    },
    {
      "typeId": 1,
      "type": "b256",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 2,
      "type": "bool",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 3,
      "type": "enum Identity",
      "components": [
        {
          "name": "Address",
          "type": 9,
          "typeArguments": null
        },
        {
          "name": "ContractId",
          "type": 13,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 4,
      "type": "enum MultisigError",
      "components": [
        {
          "name": "MaxOwnersReached",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "AlreadyOwner",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "NotOwner",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "DuplicatedOwner",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "OwnersCannotBeEmpty",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "ThresholdCannotBeZero",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "ThresholdCannotBeGreaterThanOwners",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "ThresholdNotReached",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "TransactionStillValid",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "AlreadyVoted",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "InvalidTxId",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "Unauthorized",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "NotInitialized",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "AlreadyInitialized",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "InsufficientAssetAmount",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "CanOnlyCallContracts",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "TransferRequiresAValue",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "TransactionExpired",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "MaxTransactionsReached",
          "type": 0,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 5,
      "type": "enum Option",
      "components": [
        {
          "name": "None",
          "type": 0,
          "typeArguments": null
        },
        {
          "name": "Some",
          "type": 7,
          "typeArguments": null
        }
      ],
      "typeParameters": [
        7
      ]
    },
    {
      "typeId": 6,
      "type": "enum TransactionParameters",
      "components": [
        {
          "name": "Call",
          "type": 12,
          "typeArguments": null
        },
        {
          "name": "Transfer",
          "type": 27,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 7,
      "type": "generic T",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 8,
      "type": "raw untyped ptr",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 9,
      "type": "struct Address",
      "components": [
        {
          "name": "bits",
          "type": 1,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 10,
      "type": "struct AssetId",
      "components": [
        {
          "name": "bits",
          "type": 1,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 11,
      "type": "struct Bytes",
      "components": [
        {
          "name": "buf",
          "type": 17,
          "typeArguments": null
        },
        {
          "name": "len",
          "type": 30,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 12,
      "type": "struct ContractCallParams",
      "components": [
        {
          "name": "calldata",
          "type": 11,
          "typeArguments": null
        },
        {
          "name": "forwarded_gas",
          "type": 30,
          "typeArguments": null
        },
        {
          "name": "function_selector",
          "type": 11,
          "typeArguments": null
        },
        {
          "name": "single_value_type_arg",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "transfer_params",
          "type": 27,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 13,
      "type": "struct ContractId",
      "components": [
        {
          "name": "bits",
          "type": 1,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 14,
      "type": "struct MultisigInitialized",
      "components": [
        {
          "name": "contract_id",
          "type": 13,
          "typeArguments": null
        },
        {
          "name": "threshold",
          "type": 31,
          "typeArguments": null
        },
        {
          "name": "owners",
          "type": 28,
          "typeArguments": [
            {
              "name": "",
              "type": 3,
              "typeArguments": null
            }
          ]
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 15,
      "type": "struct OwnerAdded",
      "components": [
        {
          "name": "owner",
          "type": 3,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 16,
      "type": "struct OwnerRemoved",
      "components": [
        {
          "name": "owner",
          "type": 3,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 17,
      "type": "struct RawBytes",
      "components": [
        {
          "name": "ptr",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "cap",
          "type": 30,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 18,
      "type": "struct RawVec",
      "components": [
        {
          "name": "ptr",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "cap",
          "type": 30,
          "typeArguments": null
        }
      ],
      "typeParameters": [
        7
      ]
    },
    {
      "typeId": 19,
      "type": "struct ThresholdChanged",
      "components": [
        {
          "name": "new_threshold",
          "type": 31,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 20,
      "type": "struct TransactionApproved",
      "components": [
        {
          "name": "tx_id",
          "type": 29,
          "typeArguments": null
        },
        {
          "name": "owner",
          "type": 3,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 21,
      "type": "struct TransactionCancelled",
      "components": [
        {
          "name": "tx_id",
          "type": 29,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 22,
      "type": "struct TransactionData",
      "components": [
        {
          "name": "tx_id",
          "type": 29,
          "typeArguments": null
        },
        {
          "name": "to",
          "type": 3,
          "typeArguments": null
        },
        {
          "name": "valid_until",
          "type": 30,
          "typeArguments": null
        },
        {
          "name": "tx_parameters",
          "type": 6,
          "typeArguments": null
        },
        {
          "name": "approvals_count",
          "type": 31,
          "typeArguments": null
        },
        {
          "name": "rejections_count",
          "type": 31,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 23,
      "type": "struct TransactionExecuted",
      "components": [
        {
          "name": "tx_id",
          "type": 29,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 24,
      "type": "struct TransactionProposed",
      "components": [
        {
          "name": "tx_id",
          "type": 29,
          "typeArguments": null
        },
        {
          "name": "to",
          "type": 3,
          "typeArguments": null
        },
        {
          "name": "transaction_parameters",
          "type": 6,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 25,
      "type": "struct TransactionRejected",
      "components": [
        {
          "name": "tx_id",
          "type": 29,
          "typeArguments": null
        },
        {
          "name": "owner",
          "type": 3,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 26,
      "type": "struct TransactionRemoved",
      "components": [
        {
          "name": "tx_id",
          "type": 29,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 27,
      "type": "struct TransferParams",
      "components": [
        {
          "name": "asset_id",
          "type": 10,
          "typeArguments": null
        },
        {
          "name": "value",
          "type": 5,
          "typeArguments": [
            {
              "name": "",
              "type": 30,
              "typeArguments": null
            }
          ]
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 28,
      "type": "struct Vec",
      "components": [
        {
          "name": "buf",
          "type": 18,
          "typeArguments": [
            {
              "name": "",
              "type": 7,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "len",
          "type": 30,
          "typeArguments": null
        }
      ],
      "typeParameters": [
        7
      ]
    },
    {
      "typeId": 29,
      "type": "u256",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 30,
      "type": "u64",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 31,
      "type": "u8",
      "components": null,
      "typeParameters": null
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "owner",
          "type": 3,
          "typeArguments": null
        }
      ],
      "name": "add_owner",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "tx_id",
          "type": 29,
          "typeArguments": null
        }
      ],
      "name": "approve_tx",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "threshold",
          "type": 31,
          "typeArguments": null
        }
      ],
      "name": "change_threshold",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "threshold",
          "type": 31,
          "typeArguments": null
        },
        {
          "name": "owners_list",
          "type": 28,
          "typeArguments": [
            {
              "name": "",
              "type": 3,
              "typeArguments": null
            }
          ]
        }
      ],
      "name": "constructor",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "tx_id",
          "type": 29,
          "typeArguments": null
        }
      ],
      "name": "execute_tx",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "to",
          "type": 3,
          "typeArguments": null
        },
        {
          "name": "tx_validity_duration",
          "type": 30,
          "typeArguments": null
        },
        {
          "name": "tx_parameters",
          "type": 6,
          "typeArguments": null
        }
      ],
      "name": "propose_tx",
      "output": {
        "name": "",
        "type": 29,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "tx_id",
          "type": 29,
          "typeArguments": null
        }
      ],
      "name": "reject_tx",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "owner",
          "type": 3,
          "typeArguments": null
        }
      ],
      "name": "remove_owner",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "tx_id",
          "type": 29,
          "typeArguments": null
        }
      ],
      "name": "remove_tx",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_active_tx_ids",
      "output": {
        "name": "",
        "type": 28,
        "typeArguments": [
          {
            "name": "",
            "type": 29,
            "typeArguments": null
          }
        ]
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_next_tx_id",
      "output": {
        "name": "",
        "type": 29,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_owners",
      "output": {
        "name": "",
        "type": 28,
        "typeArguments": [
          {
            "name": "",
            "type": 3,
            "typeArguments": null
          }
        ]
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_threshold",
      "output": {
        "name": "",
        "type": 31,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "tx_id",
          "type": 29,
          "typeArguments": null
        }
      ],
      "name": "get_tx",
      "output": {
        "name": "",
        "type": 5,
        "typeArguments": [
          {
            "name": "",
            "type": 22,
            "typeArguments": null
          }
        ]
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "tx_id",
          "type": 29,
          "typeArguments": null
        },
        {
          "name": "owner",
          "type": 3,
          "typeArguments": null
        }
      ],
      "name": "get_tx_approval_by_owner",
      "output": {
        "name": "",
        "type": 5,
        "typeArguments": [
          {
            "name": "",
            "type": 2,
            "typeArguments": null
          }
        ]
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "owner",
          "type": 3,
          "typeArguments": null
        }
      ],
      "name": "is_owner",
      "output": {
        "name": "",
        "type": 2,
        "typeArguments": null
      },
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": "5029799390312060703",
      "loggedType": {
        "name": "",
        "type": 4,
        "typeArguments": []
      }
    },
    {
      "logId": "4247778205116051813",
      "loggedType": {
        "name": "",
        "type": 15,
        "typeArguments": []
      }
    },
    {
      "logId": "13939973681463393299",
      "loggedType": {
        "name": "",
        "type": 20,
        "typeArguments": []
      }
    },
    {
      "logId": "16104323263592214814",
      "loggedType": {
        "name": "",
        "type": 19,
        "typeArguments": []
      }
    },
    {
      "logId": "6637065843858104832",
      "loggedType": {
        "name": "",
        "type": 14,
        "typeArguments": []
      }
    },
    {
      "logId": "2148183737622383263",
      "loggedType": {
        "name": "",
        "type": 26,
        "typeArguments": []
      }
    },
    {
      "logId": "4051544646588041829",
      "loggedType": {
        "name": "",
        "type": 23,
        "typeArguments": []
      }
    },
    {
      "logId": "8811877691347117961",
      "loggedType": {
        "name": "",
        "type": 24,
        "typeArguments": []
      }
    },
    {
      "logId": "13916806106389988781",
      "loggedType": {
        "name": "",
        "type": 25,
        "typeArguments": []
      }
    },
    {
      "logId": "4170815460413158036",
      "loggedType": {
        "name": "",
        "type": 16,
        "typeArguments": []
      }
    },
    {
      "logId": "8269000269664081973",
      "loggedType": {
        "name": "",
        "type": 21,
        "typeArguments": []
      }
    }
  ],
  "messagesTypes": [],
  "configurables": []
};

const _storageSlots: StorageSlot[] = [
  {
    "key": "02dac99c283f16bc91b74f6942db7f012699a2ad51272b15207b9cc14a70dbae",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "b48b753af346966d0d169c0b2e3234611f65d5cfdb57c7b6e7cd6ca93707bee0",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  }
];

export const FuelMultisigAbi__factory = {
  abi: _abi,

  storageSlots: _storageSlots,

  createInterface(): FuelMultisigAbiInterface {
    return new Interface(_abi) as unknown as FuelMultisigAbiInterface
  },

  connect(
    id: string | AbstractAddress,
    accountOrProvider: Account | Provider
  ): FuelMultisigAbi {
    return new Contract(id, _abi, accountOrProvider) as unknown as FuelMultisigAbi
  },

  async deployContract(
    bytecode: BytesLike,
    wallet: Account,
    options: DeployContractOptions = {}
  ): Promise<FuelMultisigAbi> {
    const factory = new ContractFactory(bytecode, _abi, wallet);

    const contract = await factory.deployContract({
      storageSlots: _storageSlots,
      ...options,
    });

    return contract as unknown as FuelMultisigAbi;
  }
}
